spring:
  application:
    name: ibm-mq-ptm
  output:
    ansi:
      enabled: always
  cloud:
    stream:
      bindings:
        mqProducer-out-0:
          destination: ptm

ptm:
  ibm:
    mq:
      queueManager: QM1
      channel: DEV.ADMIN.SVRCONN
      connName: localhost(1414)
      user: admin
      password: passw0rd

logging:
  level:
    org.springframework.cloud.stream.messaging.DirectWithAttributesChannel: DEBUG