
spring:
  application:
    name: ibm-mq-ptm
  output:
    ansi:
      enabled: always
  cloud:
    stream:
      bindings:
        mqProducer-out-0:
          destination: DEV.QUEUE.1
        mqProducerSecond-out-0:
          destination: DEV.QUEUE.2
        mqConsumerOne-in-0:
          destination: DEV.QUEUE.1
        mqConsumerSecond-in-0:
          destination: DEV.QUEUE.2
    function:
      definition: mqConsumerOne;mqConsumerSecond

ptm:
  ibm:
    mq:
      queueManager: QM1
      channel: DEV.ADMIN.SVRCONN
      connName: localhost(1414)
      user: admin
      password: passw0rd

logging:
  level:
    org.springframework.cloud.stream.messaging.DirectWithAttributesChannel: DEBUG

server:
  port: 8080